Update terraform.yml

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -78,7 +78,10 @@ jobs:
     # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
     - name: Terraform Init
       run: terraform init
-
+    
+    - name: Terraform Validate
+      run: terraform Validate
+      
     # Checks that all Terraform configuration files adhere to a canonical format
     #- name: Terraform Format
       #run: terraform fmt -check
@@ -88,11 +91,11 @@ jobs:
       run: terraform plan -input=false
     
     - name: Terraform Plan Status
-      if: steps.plan.outcome == 'failure'
-      run: exit 1
+      #if: steps.plan.outcome == 'failure'
+      #run: exit 1
     
       # On push to "main", build or change infrastructure according to Terraform configuration files
       # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
-    #- name: Terraform Apply
+    - name: Terraform Apply
       #if: github.ref == 'refs/heads/"main"' && github.event_name == 'push'
-     # run: terraform apply -auto-approve -input=false
+      run: terraform apply -auto-approve -input=false
